version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: hestia-docker
    ports:
      - 127.0.0.1:8888:80
      - 127.0.0.1:4443:443
    environment:
      - CADDY_INGRESS_NETWORKS=web
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - /usr/local/hestia/ssl:/certs:ro
    restart: unless-stopped
    labels:
     caddy: :443
     caddy.tls: "/certs/certificate.crt /certs/certificate.key"

networks:
  web:
    external: true

volumes:
  caddy_data: {}
